

let header_HTML = document.querySelector("header")
let h1_header = document.createElement("h1")
let texto_h1_header = document.createTextNode("Earth Wind & Fire")
let p_header = document.createElement("p")
let texto_p_header = document.createTextNode("Earth, Wind & Fire (EWF) is an American band that has spanned the musical genres of R&B, soul, jazz, disco e dance.")

header_HTML.appendChild(h1_header)
h1_header.appendChild(texto_h1_header)
header_HTML.appendChild(p_header)
p_header.appendChild(texto_p_header)

let main_HTML = document.querySelector("main")
let div_main1 = document.querySelector(".main1")
let h2_main1 = document.createElement("h2")
let texto_h2_main1 = document.createTextNode("Members and other features")
let p_main1 = document.createElement("p")
let texto_p_main1 = document.createTextNode("Other members of EWF have included Philip Bailey, Verdine White, Ralph Johnson, Larry Dunn, Al McKay, Roland Bautista, Robert Brookins, Sonny Emory, Fred Ravel, Ronnie Laws, Sheldon Reynolds and Andrew Woolfolk. The band is known for its kalimba sound, dynamic horn section, energetic and elaborate stage shows, and the contrast between Philip Bailey's falsetto vocals and Maurice White's baritone.")
let div_main2 = document.querySelector(".main2")
let h2_main2 = document.createElement("h2")
let texto_h2_main2 = document.createTextNode("History")
let p_main2 = document.createElement("p")
let texto_p_main2 = document.createTextNode("The band was founded in Chicago by Maurice White in 1969, having grown out of a previous band known as the Salty Peppers.")

main_HTML.appendChild(div_main1)
div_main1.appendChild(h2_main1)
h2_main1.appendChild(texto_h2_main1)
div_main1.appendChild(p_main1)
p_main1.appendChild(texto_p_main1)
div_main2.appendChild(h2_main2)
h2_main2.appendChild(texto_h2_main2)
div_main2.appendChild(p_main2)
p_main2.appendChild(texto_p_main2)

let footer_HTML = document.querySelector("footer")
let div_footer1 = document.querySelector(".footer1")
let h2_footer1 = document.createElement("h2")
let texto_h2_footer1 = document.createTextNode("Members and other features")
let p_footer1 = document.createElement("p")
let texto_p_footer1 = document.createTextNode("In the Billboard, the song September is the 113th most played in the history; 1st in Hot 100 R&B in US and 8th in Hot 100(2020 comparison list).")
let div_footer2 = document.querySelector(".footer2")
let h2_footer2 = document.createElement("h2")
let texto_h2_footer2 = document.createTextNode("History")
let p_footer2 = document.createElement("p")
let texto_p_footer2 = document.createTextNode("The band has won six Grammys from their 17 nominations and four American Music Awards out of 12 nominations.")

footer_HTML.appendChild(div_footer1)
div_footer1.appendChild(h2_footer1)
h2_footer1.appendChild(texto_h2_footer1)
div_footer1.appendChild(p_footer1)
p_footer1.appendChild(texto_p_footer1)
div_footer2.appendChild(h2_footer2)
h2_footer2.appendChild(texto_h2_footer2)
div_footer2.appendChild(p_footer2)
p_footer2.appendChild(texto_p_footer2)

// let header_HTML = document.querySelector("header")
// let h1_header = document.createElement("h1")
// let texto_h1_header = document.createTextNode("Earth Wind and Fire")
// let p_header = document.createElement("p")
// let texto_p_header = document.createTextNode("It's a Soul band")
// h1_header.appendChild(header_HTML)
// texto_h1_header.appendChild(h1_header)
// body_HTML.appendChild(header_HTML)
// texto_p_header.appendChild(p_header)

// let classeA = document.querySelector(".selecaoA")
// let classeB = document.querySelector(".selecaoB")
// let num = parseInt(prompt("Digite um número de 1 ate 10"))
// if(num<5)
// {
//     classeA.classList.remove("selecaoA")
//     classeA.classList.add("selecaoB")

//     classeB.classList.remove("selecaoB")
//     classeB.classList.add("selecaoA")
// }
// else if(num == 5)
// {
//     classeA.classList.remove("selecaoA")
//     classeA.classList.add("destaque")

//     classeB.classList.remove("selecaoB")
//     classeB.classList.add("destaque")
// }